### ISSUE TITLE
关于你的项目侵犯我的Personal_Sakura_Guide_Page和Firework_Simulator项目版权的警告

### ISSUE THREAD

**Issue by NianBroken** [sunlicp/SlcpBlog#22]
我是NianBroken，我在GitHub上发布了名为[Firework_Simulator](https://github.com/NianBroken/Firework_Simulator "Firework_Simulator")和[Personal_Sakura_Guide_Page](https://github.com/NianBroken/Personal_Sakura_Guide_Page "Personal_Sakura_Guide_Page")的开源项目，这些项目使用了**Apache-2.0**开源协议许可证。

你修改并分享了我们的[Firework_Simulator](https://github.com/NianBroken/Firework_Simulator "Firework_Simulator")和[Personal_Sakura_Guide_Page](https://github.com/NianBroken/Personal_Sakura_Guide_Page "Personal_Sakura_Guide_Page")项目，但你并**未遵守**我们明确规定的**Apache-2.0**开源协议许可证。

根据**Apache-2.0**协议的规定，你作为衍生作品的作者，**必须保留原始版权信息**，并且必须在任何衍生作品中明确指出所做的修改。

然而，**你所做的事情与此完全相悖**。你不仅没有在你的衍生作品[SlcpBlog](https://github.com/sunlicp/SlcpBlog "SlcpBlog")及其其他衍生作品中保留原始版权信息，反而还采取了令人发指的行动，**你直接将原始作者的名字改为你自己的名字**，**同时删除了所有原始版权信息**。

我们希望你清楚地意识到，对于开源项目的作者来说，保护版权是至关重要的。

你这令人发指的行为不仅是对我们努力的羞辱，也是对整个开源社区的不尊重，更是**对法律和道德的蔑视**。你的无耻行径严重侵犯了我们的权益和利益，我们绝不容忍任何侵犯知识产权的恶劣行径。

现在我们要求你立即采取紧急措施，纠正你的错误。你必须立即**在你的衍生作品**[SlcpBlog](https://github.com/sunlicp/SlcpBlog "SlcpBlog")及其其他衍生作品中**添加原始版权信息**，并确保以后不再出现任何违反开源许可证的行为。

你的行为是毫无情理可言的，我们希望你能意识到严重性，并立即行动解决问题。**任何拖延或无视将会进一步加剧你的处境**。

如果你不立即采取行动，我们将**不惜一切代价追究你的法律责任**。

**Comment by sunlicp** [comment]
我对由此引起的不便深感抱歉。这段代码是由我的同学提供的，我事先并不知情。我现在会立即进行调整。同时，你大年初三发送这样的内容让我感到不舒服，作为中国人，我对此表示不理解但再次向你道歉。




?&nbsp;?Sunflower
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunlicp/SlcpBlog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月12日(星期一) 晚上10:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sunlicp/SlcpBlog] 关于你的项目侵犯我的Personal_Sakura_Guide_Page和Firework_Simulator项目版权的警告 (Issue #22)





 
我是NianBroken，我在GitHub上发布了名为Firework_Simulator和Personal_Sakura_Guide_Page的开源项目，这些项目使用了Apache-2.0开源协议许可证。
 
你修改并分享了我们的Firework_Simulator和Personal_Sakura_Guide_Page项目，但你并未遵守我们明确规定的Apache-2.0开源协议许可证。
 
根据Apache-2.0协议的规定，你作为衍生作品的作者，必须保留原始版权信息，并且必须在任何衍生作品中明确指出所做的修改。
 
然而，你所做的事情与此完全相悖。你不仅没有在你的衍生作品SlcpBlog及其其他衍生作品中保留原始版权信息，反而还采取了令人发指的行动，你直接将原始作者的名字改为你自己的名字，同时删除了所有原始版权信息。
 
我们希望你清楚地意识到，对于开源项目的作者来说，保护版权是至关重要的。
 
你这令人发指的行为不仅是对我们努力的羞辱，也是对整个开源社区的不尊重，更是对法律和道德的蔑视。你的无耻行径严重侵犯了我们的权益和利益，我们绝不容忍任何侵犯知识产权的恶劣行径。
 
现在我们要求你立即采取紧急措施，纠正你的错误。你必须立即在你的衍生作品SlcpBlog及其其他衍生作品中添加原始版权信息，并确保以后不再出现任何违反开源许可证的行为。
 
你的行为是毫无情理可言的，我们希望你能意识到严重性，并立即行动解决问题。任何拖延或无视将会进一步加剧你的处境。
 
如果你不立即采取行动，我们将不惜一切代价追究你的法律责任。
